### ISSUE TITLE
README should indicate how to install, Rust version

### ISSUE THREAD

**Issue by xevix** [Ticki/dybuk#4]
Hey. Installing directly through Cargo doesn't work as I don't think there's a package, and the install script is currently breaking for me on Rust nightly, so I was wondering, does dybuk support nightly releases? This might be useful to add to the README.

**Comment by ticki** [comment]
Even though there are no crates.io package available, you can still do `cargo install` in the directory.

**Comment by xevix** [comment]
Ah ok. Indicating the use of `cargo install` directly as the preferred way of install would be helpful.
